detection/urls.py
from django.urls import path, re_path
from . import views

app_name = 'detection'

urlpatterns = [
    # Ana sayfa - tekli meyve tespiti
    path('', views.index, name='index'),
    path('index/', views.index, name='index_alt'),
    
    # Çoklu görüntü analizi  
    path('multi-detection/', views.multi_detection_image, name='multi_detection_image'),
    
    # Dosya indirme
    re_path(r'^download_image/(?P<slug>[\w-]+)/$', views.download_image, name='download_image'),
]

dron_map/urls.py
from django.urls import path, re_path

from . import views
app_name = 'dron_map'



urlpatterns = [
       
    path('projects', views.projects, name='projects'),     
    re_path(r'projects/(?P<slug>[\w-]+)/(?:id-(?P<id>[0-9]+)/)?$', views.add_projects, name='add_projects'),
    re_path(r'map/(?:id-(?P<id>[0-9]+)/)?$', views.maping, name='map'),
    
]

farmvision/urls.py
from django.contrib import admin
from django.urls import include, path
from user_registration import views
from django.conf.urls import handler400, handler403, handler404, handler500
from django.views.decorators.csrf import requires_csrf_token
from  django.views import defaults
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('',  include('detection.urls',namespace="index")),
    path('mcti',  include('detection.urls',namespace="multi_detection_image")),
    path('user_pr',  include('user_registration.urls',namespace="user_pr")),
    path('user_edit',  include('user_registration.urls',namespace="user_edit")),
    path('login', include('user_registration.urls',namespace="login")),
    path('calendar', include('user_registration.urls',namespace="calendar")),
    path('login_view', include('user_registration.urls',namespace="login_view")),
    path('logout', include('user_registration.urls',namespace="logout")),
    path('signup', include('user_registration.urls',namespace="signup")),
    path('forgot_password', include('user_registration.urls',namespace="forgot_password")),
    path('pricing', views.pricing, name='pricing'),
    path('map', include('dron_map.urls',namespace="map")),
    path('projects', include('dron_map.urls',namespace="projects")),
    path('add_projects', include('dron_map.urls',namespace="add_projects")),
    #path('404/', include('polls.urls',namespace="page_not_founds")),
    #path('403/', include('polls.urls',namespace="permission_denieds")),
    #path('400/', include('polls.urls',namespace="bad_requests")),
    #path('500/', include('polls.urls',namespace="server_errors")),
]

user_registration/urls.py
from django.urls import path, re_path

from . import views
app_name = 'user_registration'



urlpatterns = [
   
    re_path(r'user_pr/(?:id-(?P<id>[0-9]+)/)?$', views.user_pr, name='user_pr'),          
    re_path(r'user_edit/(?:id-(?P<id>[0-9]+)/)?$', views.user_edit, name='user_edit'),          
    path('logout', views.logout, name='logout'),
    path('pricing', views.pricing, name='pricing'),
    path('calendar', views.calendar, name='calendar'),
    path('login', views.login, name='login'),      
    path('login_view', views.login_view, name='login_view'),      
    path('signup', views.signup, name='signup'),    
    path('forgot_password', views.forgot_password, name='forgot_password'), 

]

templates/form.html
<div class="col-lg-6 col-12">
				<div class="box-content card white">
					<h4 class="box-title">Giriş deyerleri</h4>
					<!-- /.box-title -->
					<div class="card-content">
	<form id="upload-file" action="{% url 'detection:index' %}" method="post" enctype="multipart/form-data" >
		{% csrf_token %}
						<div class="form-group margin-bottom-20">
							<select name="meyve_qrupu" class="form-control">
								<option name="" value="">Meyve qrupu</option>
								<option value="mandalina">Mandalina</option>
					            <option value="elma">Elma</option>
					            <option value="armut">Armut</option>
					            <option value="seftale">Şeftali</option>
					            <option value="portakal">Portakal</option>
					            <option value="nar">Nar</option>
					            <option value="hurma">Hurma</option>    
							</select>
						</div>


						<div class="input-group margin-bottom-20">
							<div class="input-group-btn"><label for="ig-1" class="btn btn-default">
								<i class="fa-solid fa-tree"></i>
							</label></div>
							<!-- /.input-group-btn -->
							<input  type="text" name="agac_sayi" class="form-control" placeholder="Toplam Ağac Sayı">
						</div>
						<!-- /.input-group -->
						<div class="input-group margin-bottom-20">
							<div class="input-group-btn">
								<label for="ig-2" class="btn btn-default">
								<i class="fa-brands fa-pagelines"></i>
							</label></div>
							<!-- /.input-group-btn -->
							<input type="text" name="agac_yasi" class="form-control" placeholder="Ağac kaç yaşında">
						</div>
						<!-- /.input-group -->
						<div class="input-group">
							<div class="input-group-btn"><label for="ig-3" class="btn btn-default">
								<i class="fa-regular fa-chart-simple"></i>
							</label></div>
							<!-- /.input-group-btn -->
							<input  type="text" name="ekilis_sira" class="form-control" placeholder="Ekiliş sırası">
						</div>
						<!-- /.input-group -->
						<div class="form-group">
								<label for="exampleInputFile" class="btn btn-default">Meyve resmini seç <i class="ico fa-solid fa-image"></i></label>
								<input id="exampleInputFile"style="display: none" type="file" name="file" onchange="loadFile(event)">
								{% load static %}
								
								<div class="col-lg-3 col-6"> 
								<a href="#" class="thumbnail">
									<img id="output" >
								</a>
							</div>
							</div>
							<button type="submit" name="success" value="{{csrf_token}}" class="btn btn-primary btn-sm waves-effect waves-light">Submit</button>
						</form>
					</div>
					<!-- /.card-content -->
				</div>
				<!-- /.box-content card white -->
			</div>


<script>
  var loadFile = function(event) {
    var reader = new FileReader();
    reader.onload = function(){
      var output = document.getElementById('output');
      output.src = reader.result;
    };
    reader.readAsDataURL(event.target.files[0]);
  };
</script>

templates/header.html
{% if user.is_authenticated %}
  {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Home Detect and count fruit in images
</title>

	<!-- Main Styles -->
	<link rel="stylesheet" href="{% static 'assets/styles/style.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/styles/custom.css' %}">
<link rel="stylesheet" href="{% static 'assets/styles/dataTables.bootstrap4.min.css' %}">
	
	<!-- Material Design Icon -->
	<link rel="stylesheet" href="{% static 'assets/fonts/material-design/css/materialdesignicons.css' %}">
<link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

	<!-- mCustomScrollbar -->
	<link rel="stylesheet" href="{% static 'assets/plugin/mCustomScrollbar/jquery.mCustomScrollbar.min.css' %}">

	<!-- Waves Effect -->
	<link rel="stylesheet" href="{% static 'assets/plugin/waves/waves.min.css' %}">

	<!-- Sweet Alert -->
	<link rel="stylesheet" href="{% static 'assets/plugin/sweet-alert/sweetalert.css' %}">
	
	<!-- Percent Circle -->
	<link rel="stylesheet" href="{% static 'assets/plugin/percircle/css/percircle.css' %}">

	<!-- Chartist Chart -->
	<link rel="stylesheet" href="{% static 'assets/plugin/chart/chartist/chartist.min.css' %}">

	<!-- FullCalendar -->
	<link rel="stylesheet" href="{% static 'assets/plugin/fullcalendar/fullcalendar.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/plugin/fullcalendar/fullcalendar.print.css' %}" media='print'>
	<!-- Dropify -->
	<link rel="stylesheet" href="{% static 'assets/plugin/dropify/css/dropify.min.css' %}">
	


	<!-- Color Picker -->
	<link rel="stylesheet" href="{% static 'assets/color-switcher/color-switcher.min.css' %}">
</head>
<body>
	      {% block body %}
	      
{%endblock%}


<script src="{% static 'assets/scripts/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/scripts/modernizr.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugin/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugin/mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugin/nprogress/nprogress.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugin/sweet-alert/sweetalert.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugin/waves/waves.min.js' %}" type="text/javascript"></script>
<!-- Full Screen Plugin -->
<script src="{% static 'assets/plugin/fullscreen/jquery.fullscreen-min.js' %}" type="text/javascript"></script>

<!-- Google Chart -->
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<!-- chart.js Chart -->

<script src="{% static 'assets/scripts/chart.sparkline.init.min.js' %}" type="text/javascript"></script>
<!-- FullCalendar -->
<script src="{% static 'assets/plugin/moment/moment.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugin/fullcalendar/fullcalendar.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/scripts/fullcalendar.init.js' %}" type="text/javascript"></script>

<!-- Sparkline Chart -->
<script src="{% static 'assets/plugin/chart/sparkline/jquery.sparkline.min.js' %}" type="text/javascript"></script>

<script src="{% static 'assets/plugin/dropify/js/dropify.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/scripts/main.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/scripts/mycommon.js' %}" type="text/javascript"></script>

<script src="{% static 'assets/scripts/jquery.dataTables.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/scripts/datatables.demo.min.js' %}" type="text/javascript"></script>

<script src="{% static 'assets/color-switcher/color-switcher.min.js' %}" type="text/javascript"></script>

</body>
	</html>
	{% else %}
<p>Please login to see this page.</p>
    {% endif %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Home</title>

<link rel="stylesheet" href="{% static 'assets/styles/style.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/styles/custom.css' %}">
	<!-- Waves Effect -->

	<link rel="stylesheet" href="{% static 'assets/plugin/waves/waves.min.css' %}">
</head>

<body>

<div id="single-wrapper">
	<form action="{% url 'user_registration:login_view' %}" method="post" class="frm-single">
		{% csrf_token %}
		<div class="inside">
			<div class="title"><strong>Login </strong></div>
			<!-- /.title -->
			
			<!-- /.frm-title -->
			<div class="frm-input"><input type="text" name="username" placeholder="Username" class="frm-inp"><i class="fa fa-user frm-ico"></i></div>
			<!-- /.frm-input -->
			<div class="frm-input"><input type="password" name="password" placeholder="Password" class="frm-inp"><i class="fa fa-lock frm-ico"></i></div>
			<!-- /.frm-input -->
			<div class="clearfix margin-bottom-20">
			
				<!-- /.float-left -->
				<div class="float-right"><a href="{% url 'user_registration:forgot_password' %}" class="a-link"><i class="fa fa-unlock-alt"></i>Forgot password?</a></div>
				<!-- /.float-right -->
			</div>
			<!-- /.clearfix -->
			<button type="submit" class="frm-submit">Login<i class="fa fa-arrow-circle-right"></i></button>
			
			<!-- /.row -->
			<a href="{% url 'user_registration:signup' %}" class="a-link"><i class="fa fa-key"></i>Don't have an account ? Sign Up.</a>
			<div class="frm-footer">Admin © 2023.</div>
			<!-- /.footer -->
		</div>
		<!-- .inside -->
	</form>
	<!-- /.frm-single -->
</div>
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="assets/scripts/jquery.min.js" type="c7238fc848d009e02302ef02-text/javascript"></script>
	<script src="assets/scripts/modernizr.min.js" type="c7238fc848d009e02302ef02-text/javascript"></script>
	<script src="assets/plugin/bootstrap/js/bootstrap.min.js" type="c7238fc848d009e02302ef02-text/javascript"></script>
	<script src="assets/plugin/nprogress/nprogress.js" type="c7238fc848d009e02302ef02-text/javascript"></script>
	<script src="assets/plugin/waves/waves.min.js" type="c7238fc848d009e02302ef02-text/javascript"></script>

	<script src="assets/scripts/main.min.js" type="c7238fc848d009e02302ef02-text/javascript"></script>
<script src="assets/scripts/mycommon.js" type="c7238fc848d009e02302ef02-text/javascript"></script>
<script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="c7238fc848d009e02302ef02-|49" defer=""></script></body>
</html>

templates/map2.html
{% extends 'header.html' %}
{% block body %}
      {% load static %}
      {% include 'menu3.html' with picture=projes.picture%}
      {% include 'navbar.html' with picture=userss.picture  orthophoto=orthophoto static=static%}
      <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
      integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
      crossorigin=""/>
      <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
      integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM="
      crossorigin=""></script>
      
      <script src="https://unpkg.com/georaster"></script>
      <script src="https://unpkg.com/proj4"></script>
      <script src="https://unpkg.com/georaster-layer-for-leaflet"></script>
      <style>
        #map {
            
            width:100%;
            height: 90hv;
        }
        
        .leaflet-container {
            width:100%;
            height: 90vh;
        }
        
        </style>
        
        <div id="wrapper">
            <div class="main-content">
                {{projes.hashing_path}}
                {{orthophoto}}
                {{static}}
                  <div class="row small-spacing">
<div id="map"></div>
                  </div>
                  </div>
                </div>
      

<script >   

var popup = L.popup();
var map = L.map('map').setView([0, 0], 5);

var osm = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    markerZoomAnimation: true,
    zoomControl: true,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
}).addTo(map);






function onMapClick(e) {
    popup
        .setLatLng(e.latlng)
        .setContent("lat " + e.latlng.lat+ "  lng  " +e.latlng.lng)
        .openOn(map);
}

map.on('click', onMapClick);







googleStreets = L.tileLayer('http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}',{
        maxZoom: 20,
        subdomains:['mt0','mt1','mt2','mt3']
}).addTo(map);
googleHybrid = L.tileLayer('http://{s}.google.com/vt/lyrs=s,h&x={x}&y={y}&z={z}',{
        maxZoom: 20,
        subdomains:['mt0','mt1','mt2','mt3']
}).addTo(map);
googleSat = L.tileLayer('http://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',{
        maxZoom: 20,
        subdomains:['mt0','mt1','mt2','mt3']
}).addTo(map);
googleTerrain = L.tileLayer('http://{s}.google.com/vt/lyrs=p&x={x}&y={y}&z={z}',{
        maxZoom: 20,
        subdomains:['mt0','mt1','mt2','mt3']
}).addTo(map);


var singleMarker = L.marker([0,0]);
singleMarker.addTo(map);

var baseLayers = {
    "Satellite":googleSat,
    "Open Street Map": osm,
    "Google Map":googleStreets,
    "Google Terrain":googleTerrain,
    "Google Hybrid":googleHybrid
};

var overlays = {
    
    "Marker": singleMarker,
};

L.control.layers(baseLayers).addTo(map);

var url_to_geotiff_file = "{% static 'results/12ba54608984c587066a56929ef2c2f86e166e90/odm_orthophoto/odm_orthophoto.tif' %}";

fetch(url_to_geotiff_file)
  .then(response => response.arrayBuffer())
  .then(arrayBuffer => {
    parseGeoraster(arrayBuffer).then(georaster => {
      console.log("georaster:", georaster);

      /*
          GeoRasterLayer is an extension of GridLayer,
          which means can use GridLayer options like opacity.

          Just make sure to include the georaster option!

          Optionally set the pixelValuesToColorFn function option to customize
          how values for a pixel are translated to a color.

          https://leafletjs.com/reference.html#gridlayer
      */
      var layer = new GeoRasterLayer({
        georaster: georaster,
        opacity: 1,
        resolution: 512
      });
      layer.addTo(map);

      map.fitBounds(layer.getBounds());

  });
});
      </script>


{% endblock %}

templates/menu3.html
{% load static %}

<script src="{% static 'stylesheets/multirange.css' %}" type="text/javascript"></script>
<script src="{% static 'javascripts/multirange.js' %}" type="text/javascript"></script>


<div class="main-menu">
	<header class="header">
		<a href="{% url 'detection:index' %}" class="logo">CoreMeda</a>
		<button type="button" class="button-close fa fa-times js__menu_close"></button>
	</header>
	<!-- /.header action="{{ request.path|urlencode }}" -->
	<div class="content">
        <form  method="post" enctype="multipart/form-data">
            {% csrf_token %}
		<div class="navigation">
			<ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link" id="home-tab" data-toggle="tab" href="#Imagedetails" role="tab" aria-controls="home" aria-selected="true"><i class="menu-icon fa-solid fa-leaf"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#Analysis" role="tab" aria-controls="profile" aria-selected="false"><i class="menu-icon fa-solid fa-chart-line"></i></a>
                </li>
				
			</ul>
			<!-- /.menu js__accordion -->
            <div class="tab-content card white" id="myTabContent">
                <div class="tab-pane fade active show" id="Imagedetails" role="tabpanel" aria-labelledby="home-tab">
                    

        <p>
        <h2>Tiled Vegetation Index</h2>
        <strong style='color:rgb(156, 158, 158);'>Average GSD:</strong><p>{{static.gsd}} cm</p>
        <strong style='color:rgb(156, 158, 158);'>Area:</strong><p>{{static.area}} m&sup2;</p>
        <strong style='color:rgb(156, 158, 158);'>Date Created on:</strong><p>{{static.date}}</p>
        <strong style='color:rgb(156, 158, 158);'>Camera:</strong><p>{{images_info.camera_model}}</p>
        <strong style='color:rgb(156, 158, 158);'>Altitude:</strong><p>{{images_info.altitude}}</p>
        {% if orthophoto.ranges is not None %}
        <strong style='color:rgb(156, 158, 158);'>Detection:</strong><p style='color:red;font-weight: bold;'>{{detection}}</p>
        {% endif %}
        </p>
                </div>
                <div class="tab-pane fade " id="Analysis" role="tabpanel" aria-labelledby="profile-tab">
                    
                    <label>Histogram Chart</label>
                    <!-- Add a slider -->
                   
                    {% if orthophoto.ranges is not None %}
                  <input type="range" id="myRange" name="range" multiple  max="1" min="-1" step="0.001" />
                  <p>Value: {{orthophoto.ranges}}<span id="demo"></span></p>
                  {% else %}
                  <input type="range" name="range" multiple  max="1" min="-1" step="0.001" id="myRange"/>
                  <p>Value: <span id="demo"></span></p>
                  {% endif %}
                  
                    <p>
                        
                        
                        <label for="base">Algorithm:</label>
                        <select class="form-control" name="health_color" id="base">                        
                            {% for key,values in algo.items %}
                            
                                {{values|safe}}
                            
                            {% endfor %}

                        </select>
                    </p>
                    <p><label for="base">Colors:</label>
                        <select class="form-control" name="cmap">
                            {% for color in colors.items %}
                                {{color|safe}}
                            {% endfor %}
                        </select>
                        </p>
                   <p><button name="checked" type="submit" class="btn btn-primary btn-sm waves-effect waves-light">Check</button></p>
                                    </div>
            </div>
            
        
		</div>
		<!-- /.navigation -->
	</div>
</form>
	<!-- /.content -->
</div>
<!-- /.main-menu -->

<script>
    var slider = document.getElementById("myRange");
    var output = document.getElementById("demo");
    output.innerHTML = slider.value;
    
    slider.oninput = function() {
      output.innerHTML = this.value;
    }
    </script> 

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Home</title>
	<link rel="stylesheet" href="{% static 'assets/styles/style.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/styles/custom.css' %}">
		<!-- Waves Effect -->
	
		<link rel="stylesheet" href="{% static 'assets/plugin/waves/waves.min.css' %}">

</head>

<body>

<div id="single-wrapper">
	<form action="{% url 'user_registration:signup' %}" method="post" class="frm-single">
		{% csrf_token %}
		<div class="inside">
			<div class="title"><strong>Sign Up</strong></div>
			<!-- /.title -->
			
			<!-- /.frm-title -->
			<div class="frm-input"><input type="email" name="email" placeholder="Email" class="frm-inp"><i class="fa fa-envelope frm-ico"></i></div>
			{% if form.errors.email != None %}
			<div class="alert alert-danger alert-dismissible" role="alert"> 
				
				<strong>{{ form.errors.email }}</strong> 
			</div>
			{% else %}
			{% endif %}
			<div class="frm-input"><input type="text" placeholder="Username" name="username" class="frm-inp"><i class="fa fa-user frm-ico"></i></div>
			{% if form.errors.username != None %}
			<div class="alert alert-danger alert-dismissible" role="alert"> 
				
				<strong>{{ form.errors.username }}</strong> 
			</div>
			{% else %}
			{% endif %}
			<div class="frm-input"><input type="password" name="password1" placeholder="Password" class="frm-inp"><i class="fa fa-lock frm-ico"></i></div>
			{% if form.errors.password1 != None %}
			<div class="alert alert-danger alert-dismissible" role="alert"> 
				
				<strong>{{ form.errors.password1 }}</strong> 
			</div>
			{% else %}
			{% endif %}
			<div class="frm-input"><input type="password" name="password2" placeholder="Password" class="frm-inp"><i class="fa fa-lock frm-ico"></i></div>
			<!-- /.frm-input -->
			{% if form.errors.password2 != None %}
			<div class="alert alert-danger alert-dismissible" role="alert"> 
				
				<strong>{{ form.errors.password2 }}</strong> 
			</div>
			{% else %}
			{% endif %}
			<!-- /.clearfix -->
			
			<input type="text" name="date_joined" placeholder="date_joined" class="frm-inp" value="{% now "jS F Y H:i" %}">
			{% if form.errors.date_joined != None %}
			<div class="alert alert-danger alert-dismissible" role="alert"> 
				
				<strong>{{ form.errors.date_joined }}</strong> 
			</div>
			{% else %}
			{% endif %}
			<button type="submit" class="frm-submit">Sign Up<i class="fa fa-arrow-circle-right"></i></button>
		
			<!-- /.row -->
			<a href="{% url 'user_registration:login' %}" class="a-link"><i class="fa fa-sign-in"></i>Already have account? Sign in.</a>
			<div class="frm-footer">Admin © 2023.</div>
			<!-- /.footer -->
		</div>
		<!-- .inside -->
	</form>
	<!-- /.frm-single -->
</div><!--/#single-wrapper -->

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
		<script src="assets/script/html5shiv.min.js"></script>
		<script src="assets/script/respond.min.js"></script>
	<![endif]-->
	<!-- 
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="assets/scripts/jquery.min.js" type="c711b7cc6e061d3aef212a83-text/javascript"></script>
	<script src="assets/scripts/modernizr.min.js" type="c711b7cc6e061d3aef212a83-text/javascript"></script>
	<script src="assets/plugin/bootstrap/js/bootstrap.min.js" type="c711b7cc6e061d3aef212a83-text/javascript"></script>
	<script src="assets/plugin/nprogress/nprogress.js" type="c711b7cc6e061d3aef212a83-text/javascript"></script>
	<script src="assets/plugin/waves/waves.min.js" type="c711b7cc6e061d3aef212a83-text/javascript"></script>

	<script src="assets/scripts/main.min.js" type="c711b7cc6e061d3aef212a83-text/javascript"></script>
<script src="assets/scripts/mycommon.js" type="c711b7cc6e061d3aef212a83-text/javascript"></script>
<script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="c711b7cc6e061d3aef212a83-|49" defer=""></script></body>
</html>